# .air.toml
root = "."
tmp_dir = "tmp"

[build]
# Build command
cmd = "go build -o ./tmp/ginx ./cmd/..."
# Binary file produced by the build command
bin = "./tmp/ginx"
# Full path to the binary to run after build
full_bin = "./tmp/ginx"
# File extensions to watch
include_ext = ["go", "tpl", "tmpl", "html"]
# Directories to watch
include_dir = ["cmd", "internal", "pkg"]
# It's not necessary to trigger build each time file changes if it's too frequent
delay = 1000 # ms
# Stop running old binary when build errors occur
stop_on_error = true
# Send Interrupt before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt
kill_delay = 500 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true