services:
  app:
    container_name: ginx
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ulimits:
      nofile:
        soft: ${MAX_OPEN_FILES}
        hard: ${MAX_OPEN_FILES}
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      CONFIG_PATH: ${CONFIG_PATH}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - httpbin1
      - httpbin2
    networks:
      - ginx

  # First HTTP test server
  httpbin1:
    image: kennethreitz/httpbin
    container_name: httpbin1
    ports:
      - "8081:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    networks:
      - ginx

  # Second HTTP test server
  httpbin2:
    image: kennethreitz/httpbin
    container_name: httpbin2
    ports:
      - "8082:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    networks:
      - ginx

networks:
  ginx:
    driver: bridge